import Layout from '@/components/layout';
import Head from 'next/head';
import MatchList from '@/components/matchList';
import Profile from '@/components/profile';
import { IMatchData, IProfileData, searchMatchDetail, searchMatchIds, searchProfile } from '@/lib/search';

interface ISummonerProps {
  profileData: IProfileData,
  matchesData: IMatchData[]
}

interface ISummonerName {
    params: {name: string};
}

export async function getServerSideProps({ params }: ISummonerName) {
  const profileData: IProfileData | null = await searchProfile(params.name);
  const matchIdsData: string[] | null = await searchMatchIds(profileData!.puuid, 0, 10);
  const matchesData: (IMatchData | null)[] = await Promise.all(
    matchIdsData!.map(
      async (matchId) => searchMatchDetail(matchId, params.name)
    )
  );

  return {
    props: {
      profileData,
      matchesData
    }
  }
}

export default function Summoner(props: ISummonerProps) {

  return (
    <Layout>
      <Head>
        <title>{`${props.profileData.name} - Search Summoner`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {props.profileData && <Profile data={props.profileData}/>}
      {props.matchesData && <MatchList data={props.matchesData}/>}
    </Layout>
  );
}